version: '2'

volumes:
    database_data:
        driver: local

services:
  nginx:
      image: nginx:latest
      ports:
          - 80:80
      volumes:
          - ./docker/nginx/herstelkamer.nl.conf:/etc/nginx/conf.d/default.conf
      volumes_from:
          - php
  php:
      build: ./docker/php-fpm/
      expose:
          - 9000
      volumes:
          - .:/var/www/html
  mysql:
      image: mysql:latest
      expose:
          - 3306
      volumes:
          - database_data:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: dev
          MYSQL_DATABASE: herstelkamer
          MYSQL_USER: herstelkamer
          MYSQL_PASSWORD: herstelkamer
